// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jkrwgbcliqxpnehtcgnk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImprcndnYmNsaXF4cG5laHRjZ25rIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEyODA3OTUsImV4cCI6MjA2Njg1Njc5NX0.2OZ1XHPZRk3Pe5LuvgHZG3pdar6FljulvQRQFnIIQJA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});